name: publish

on: [push]

jobs:
    build:
        name: Cloud Run Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup GCP Service Account
              uses: google-github-actions/setup-gcloud@master
              with:
                  version: "latest"
                  service_account_email: ${{ secrets.GCP_EMAIL }}
                  service_account_key: ${{ secrets.GCP_KEY }}
                  export_default_credentials: true
            - name: Configure Docker
              run: |
                  gcloud auth configure-docker

            - name: Build
              run: |
                  docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/tubes:latest .
            - name: Push
              run: |
                  docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/tubes:latest
            - name: Deploy
              run: |
                  gcloud run deploy tubes \
                  --region asia-southeast1 \
                  --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/tubes \
                  --set-env-vars=[${{ secrets.RELEASE }}] \
                  --platform managed \
                  --allow-unauthenticated \
                  --project ${{ secrets.GCP_PROJECT_ID }}
