name: test

on: [push, workflow_dispatch]

jobs:
    build:
        name: Test Actions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Start Action
              run: |
                echo "TES ACTION"
